### PR TITLE
Update Data Files Coord-sets.xml Wxfax-Inet.xml

### PR DESCRIPTION
**Pull request by rgleason**
Have gone through Inet Retrieval  NOAA bos, reynes, n.orleans, honalulu, kodiak.  Also have added OPC charts (new.  Also updated NOAA OPC (shortened name, too long for my screen) and checked and fixed all those.   There are a few satellite images I could not get working. I can list those later If you would like, so you could try to fix them.  Note the other sections have not been touched. I notice that a number of them need updates. I will promote this User activity on the forum.  Hope this works. Rejiggered my Workflow so now I think it is correct.  1. Fetch merge from sean to local. 2. Push to rgleason to keep my repository current. 3. If have changes push to rgleason in a separate branch, very important. 4. Then make PR.

### CODE REVIEW

**Comment by rgleason** [comment]
I wonder why this is going to seandepagnier:master. 
If there was an automatic way for me to create a "mirror branch" in sean's repository called "xmlupdate" then I could make a pull request to that same branch!
Then Sean could pull it into Master whenever he wanted.

How should I be doing this part?

**Comment by seandepagnier** [comment]
You can make the branch in your own repository.

**Comment by rgleason** [comment]
Humm, I am not doing something right because I had entered all the changes into a new branch "xmludate" on my PC and then 'git push origin xmlupdates'   Then found that branch in my github account and made the Pull Request to your account. It seemed to put it into seandepagnier/weatherfax_pi/master     -Maybe I need to be more careful at that point.

**Comment by nohal** [comment]
There is nothing wrong, this is how it works. You can't force-create branches in Sean's repository using pull requests.
When creating the pull request, you may select agains which upstream branch you want to do it, but that branch must already exist in Sean's upstream repository. Master, being the default, is perfectly appropriate in this particular case.

**Comment by rgleason** [comment]
I see now,  when I reached "Comparing Changes" I should have dropped down your [branches] menu and added "xmlupdates"  !

I guess I can close this now, or delete the branch?

**Comment by rgleason** [comment]
Thanks Pavel, just saw this.
"When creating the pull request, you may select agains which upstream branch you want to do it, but that branch must already exist in Sean's upstream repository. Master, being the default, is perfectly appropriate in this particular case"

I noticed that I could dropdown branches under sean's side and there was an empty field that I thought I could enter "xmlupdates" into.   I guess I would have been stopped as I don't have that right to create branches in Sean's repos.

**Comment by nohal** [comment]
Your pull request has been merged (and closed) 3 hours ago, there is nothing to close left. And yes, you can delete the branch in your own repository as it's mission is now over...

**Comment by rgleason** [comment]
Thanks.

**Pull request merged**
