### PR TITLE
ov50 - appveyor.yml changes

### PR DESCRIPTION
**Pull request by rgleason**
Attempt to compile for Windows Opencpn mui4.99.1408 with necessary changes to appveyor using MSVS 2017 and wxWidgets 3.1.2.  There may be other changes required to this and other files.

Use of  "snprintf"  in a number of files causes errors. I can not fix.

### CODE REVIEW

**Comment by rgleason** [comment]
50 Warnings 39 Errors
Typical:
>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration [C:\project\weatherfax_pi\build\weatherfax_pi.vcxproj]

https://stackoverflow.com/questions/52179282/vs2017-error-macro-definition-of-snprintf-conflicts-with-standard-library-fu

Search for:
`#define snprintf _snprintf
`
Perhaps use:

```
#if _MSC_VER < 1700 
#define snprintf _snprintf
#endif

```

**Comment by seandepagnier** [comment]
I am not merging until zero errors.

**Comment by rgleason** [comment]
Thanks, not expected, but I've taken it as far as I could. I  don't know how to fix these problems, can you give me some clue how?

**Comment by rgleason** [comment]
This link makes me think that perhaps sourceforge was slow again and switched to try to compile x64!
https://github.com/Automattic/node-canvas/issues/619

I am going to try a small change to force appveyor to compile again. Is there an easier/quicker way to force another compile?

**Comment by rgleason** [comment]
Perhaps someone removed this file?  PVW32Con.exe  from sourceforge?

```
cd c:\project\weatherfax_pi
cd buildwin
Start-FileDownload **https://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/PVW32Con.exe**
Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
Inner Exception: Unable to connect to the remote server
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:242 char:2
+     Start-FileDownloadInternal -Url $Url -FileName $FileName -Timeout ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-FileDownloadInternal], Exception
    + FullyQualifiedErrorId : System.Exception,Appveyor.BuildAgent.Api.Utils.StartFileDownloadInternalCmdlet
 
cd ..
mkdir build
```

After looking at sourceforge, there is a package file now.  This path in the plugin seems quite old for some reason....

https://downloads.sourceforge.net/project/opencpnplugins/weatherfax_pi/wf_depends.7z

**Comment by rgleason** [comment]
It still fails with the same failures. I have to stop now and leave this for someone else to fix.

stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration [C:\project\weatherfax_pi\build\weatherfax_pi.vcxproj]

**Pull request closed without merging**
