### PR TITLE
Explicitely add -O2 and -fPIC to the compile flags for Linux.

### PR DESCRIPTION
**Pull request by stelian42**

### CODE REVIEW

**Comment by did-g** [comment]
Hi,
In my understanding this patch is wrong. 
cmake  -DCMAKE_BUILD_TYPE=
already takes care of compiler switches, hard coding them add nothing, as a matter of fact -g should be removed, ie you can't build a Release version without debugging information .
 
cmake  -DCMAKE_BUILD_TYPE=RelWithDebInfo 
is the proper spell for -O2 -g

**Comment by stelian42** [comment]
You're correct, I didn't know about the CMAKE_BUILD_TYPE.

However, what about fPIC ? It works ok on Linux (it is added automatically by cmake), but I recall Pavel had issues on MacOS because this flag wasn't set.

So maybe we should remove both -g and -Ox from PluginConfigure.cmake, but keep fPIC (and do this for all the plugins).

**Comment by seandepagnier** [comment]
I am not sure about fpic, seems to be ok.. Can we close this (no merge)?

**Comment by did-g** [comment]
Hi,
I don't know about PIC on OSX for testing I pushed a slightly modified travis and it seems to be ok:

https://travis-ci.org/did-g/weatherfax_pi/builds/360964933

I haven't executed it though, maybe it's an old issue? Or something else.

**Comment by stelian42** [comment]
Yes of course, let's close this for now.

**Pull request closed without merging**
