### PR TITLE
Fix in-the-tree build

### PR DESCRIPTION
**Pull request by nohal**
Same improvements as usually. SRC_TINYXML is renamed to SRC_LTINYXML because it is defined in the core and even though not needed at all on linux and correctly disabled in the plugin, cmake fails.

### CODE REVIEW

**Comment by transmitterdan** [comment]
There is a small error in CMakeLists.txt. The line:

INCLUDE("cmake/PluginConfigure.cmake")

should appear before:

IF (MSVC)

Also, when building this under Windows the library portaudio_x86.lib is not found. Is this supposed to be part of the git or does it come from some other prerequisite package that should be installed in Windows first?

**Comment by rgleason** [comment]
look under sourcforge/opencpnplugins/wf-depends.gz  or something like that.
I put those files under buildwin if doing NSIS cpack install exe.

**Comment by rgleason** [comment]
Actually
http://sourceforge.net/projects/opencpnplugins/files/weatherfax_pi/wf_depends.7z/download

All the files should be unpacked into buildwin directory.

**Comment by rgleason** [comment]
Sean does have this in the Readme, but I added a few lines.
https://github.com/rgleason/weatherfax_pi/commit/6ab5e968ea77db549f9a6daa811a192007e49d7e

**Pull request merged**
