### PR TITLE
Update to include the data files in the OSX package

### PR DESCRIPTION
**Pull request by ptulp**
Updated the PluginLocalization.cmake and pkgproj file to include the
data files in the OSX package.

### CODE REVIEW

**Comment by ptulp** [comment]
Did the same kind of update as to the weather_routing plugin to include the data file in the OSX package.

**Comment by nohal** [comment]
Peter...
Just a question - why PluginLocalization? Shouldn't this stuff better go to PluginPackage.cmake?

**Comment by ptulp** [comment]
I don't know if the pkgproj file can handle finding the data files if they are not in the build directory tree.
I looked at the po file handling and kind of copied it.
I have no knowledge of handling it in the PluginPackage.cmake file. I am not that familiar with cmake handling actually.

**Comment by ptulp** [comment]
OK, I looked at it again and you only need an update on the pkgproj file to find the data files on the original place.

**Pull request merged**
