### PR TITLE
Use system tinyxml if it's available

### PR DESCRIPTION
**Pull request by SethDart**

### CODE REVIEW

**Comment by seandepagnier** [comment]
why do we want to do this?

**Comment by SethDart** [comment]
Because on most Linux distro, it's already packaged and (well?!?) maintained. Better use this one instead of ours if available.

We already do this on core OpenCPN and other plugins.

If we want it officially packaged some day in those distro, they'll require us to do so (as required per packaging policies). I'm already doing so for my Fedora/CentOS packages and I guess Pavel also does for Ubuntu/Debian.

Thanks.

**Comment by rgleason** [comment]
This is getting pretty old. Didn't Sean fix it already?

**Comment by seandepagnier** [comment]
I think it uses the system tinyxml now if possible.

Closing this.

**Pull request closed without merging**
