### PR TITLE
Xml update, stelian miscell ui fixes, ov50 appveyor,  "ov50" in file name

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
Sean, I am going to put the ov42 and ov50 versions into github "Releases", but I very much like to get the Windows Release files automatically uploaded to your github "Releases" somehow.  Then I will stop making the window release files.

**Comment by seandepagnier** [comment]
Doesn't appveyor make releases automatically?

**Comment by nohal** [comment]
> Doesn't appveyor make releases automatically?

It can if configured so

**Comment by rgleason** [comment]
The appveyor file created is not successfully uploaded to github unless the proper permission is given.
IE: The windows appveyor file can be successfully created and actually exist in the "Artifacts" Tab, but if the github authorization & security is not set up, there will be a red X on appveyor with a 401 Fail note, because the successfully created appveyor file is not uploaded to github "Release".

I will get my repository working, next and advise further, however these PR need to be merged.

**Comment by rgleason** [comment]
Sean I see you just merged the first three. Thank you.
The conflicting file for ov50 - PR #131 is VERSION.cmake and the conflict is
created by  the change to ov50 I think.

- <<<<<<< xml-update-stelian-ov50-appveyor-cmake
- SET(NAME_SUFFIX "ov50")
- =======
- SET(NAME_SUFFIX "ov42")
- >>>>>>> master
- 

How would I resolve this?

**Comment by rgleason** [comment]
Maybe I should just make a new PR for ov50?
Perhaps that is easiest.

**Comment by rgleason** [comment]
Sean, I am going to close this and make a new one.  Something doesn't look right with appveyor

**Comment by rgleason** [comment]
No, not for the windows exe.  
I have been working on this problem and I have it configured correctly, except I believe that I don't have the right authorizations.

First I tried a  Public key  appveyor deploy key. That did not work.

The I tried an Oauth authorization  - Personal Token with Yaml encryption of the public key after checking the "repo" scope.   I might need to check an additional "scope" beyond  "repo", perhaps check "admin.hook"

I've been at this for days, drip drip and doing other things too. I am not going to stop until I get it right.

The error message is consistently 
> Error creating GitHub release: Provider setting not found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML was exported) while being logged under correct account. Parameter name: auth_token

The two appveyor posts I've created are:

https://help.appveyor.com/discussions/questions/36989-does-full-control-of-repository-hooks-grant-read-write-if-auth-is-ok

https://help.appveyor.com/discussions/problems/23134-push-built-file-to-opensource-public-github-release

Nobody really helps there.

I know it is a security problem from this
https://github.com/settings/security

I do not know if I need to be an "organization". I hope not.

**Pull request closed without merging**
