### PR TITLE
remove OCPN_DLDS_CONN_SETTINGS_ALL

### PR DESCRIPTION
**Pull request by nkiesel**
These cause an assertion failure (visible when compiling for debug) and it anyway
seems that the download dialog does not allow to configure auth, port, or proxy
when downloading from the Internet.

### CODE REVIEW

**Comment by seandepagnier** [comment]
I cannot merge this because it is in a file included in every plugin which is not allowed to be modified.

You should submit this pull request to the core (OpenCPN/OpenCPN) if it is indeed correct which I am doubtful.

What assert fails?  I compile in debug myself.

**Comment by nkiesel** [comment]
See attached backtrace.

What I did to get there is to open the plugin, select "Retrieve Internet", then select any file and click on "Retrieve Selected".  The assertion passes with the patch from this pull request.
[backtrace.txt](https://github.com/seandepagnier/weatherfax_pi/files/304165/backtrace.txt)

**Comment by seandepagnier** [comment]
[4] OCPN_downloadFile(wxString const&, wxString const&, wxString const&, wxString const&, wxBitmap const&, wxWindow*, long, int) /home/nkiesel/Projects/O/OpenCPN/src/pluginmanager.cpp:5439


This is the last place it is in opencpn code.  This problem would happen in all plugins, so I suggest we fix OpenCPN.

Perhaps we can mask out this flag in pluginmanager.cpp in the meantime or something.  really pavel should comment on this.

**Comment by nkiesel** [comment]
I will try to engage Pavel.  However, another possible fix within the realm of this plugin would be to replace `OCPN_DLDS_SHOW_ALL` in `InternetRetrievalDialog.cpp` with `OCPN_DLDS_ELAPSED_TIME|OCPN_DLDS_ESTIMATED_TIME|OCPN_DLDS_REMAINING_TIME|
    OCPN_DLDS_SPEED|OCPN_DLDS_SIZE|OCPN_DLDS_URL` (i.e. the current value w/o `OCPN_DLDS_CONN_SETTINGS_ALL`).

**Comment by nkiesel** [comment]
Anyway I will close this pull request. Depending on discussion with Pavel I might open another one with the change to `InternetRetrievalDialog.cpp`.

**Pull request closed without merging**
