### PR TITLE
Fix compiling with GCC 7.x

### PR DESCRIPTION
**Pull request by free-x**
Hi Sean,

please pull this change. It fixes compiling with GCC 7.[23].x
[https://github.com/seandepagnier/weatherfax_pi/issues/52](url)

regards
free-x

### CODE REVIEW

**Comment by jcollie** [comment]
Adding -fpermissive will work around the problem, but I think that it would be better to replace the problematic bit shifts.

**Comment by nohal** [comment]
FWIW it seems to be fixed in libaudiofile upstream by https://github.com/mpruett/audiofile/commit/b62c902dd258125cac86cd2df21fc898035a43d3

**Comment by rgleason** [comment]
I believe this should be closed now, as Pavel reports it is fixed upstream. Either Sean or Free-X have to close it.

**Comment by rgleason** [comment]
Sean, I believe this can be closed.

**Comment by nohal** [comment]
This can not be closed until the upstream fixes are also pulled to the local copy of `libaudiofile`...

**Pull request closed without merging**
